# Generated by Django 6.0.4 on 2026-04-08 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stalls', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalAgreement',
            fields=[
                ('agreement_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('rental_status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended')], default='active', max_length=10)),
                ('stall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='stalls.stall')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='vendors.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('penalty_id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('penalty_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_issued', models.DateField(auto_now_add=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='rentals.rentalagreement')),
            ],
            options={
                'verbose_name_plural': 'Penalties',
            },
        ),
        migrations.CreateModel(
            name='RentalHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='rentals.rentalagreement')),
            ],
            options={
                'verbose_name_plural': 'Rental Histories',
            },
        ),
    ]
