# Generated by Django 6.0.4 on 2026-04-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
