# Generated by Django 6.0.4 on 2026-04-08 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('market_id', models.AutoField(primary_key=True, serialize=False)),
                ('market_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=255)),
                ('operating_hours', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StallCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Stall Categories',
            },
        ),
        migrations.CreateModel(
            name='Stall',
            fields=[
                ('stall_id', models.AutoField(primary_key=True, serialize=False)),
                ('stall_number', models.CharField(max_length=20, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('operating_hours', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('occupied', 'Occupied'), ('vacant', 'Vacant')], default='vacant', max_length=10)),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stalls', to='stalls.market')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stalls', to='stalls.stallcategory')),
            ],
        ),
    ]
