# Generated by Django 6.0.4 on 2026-05-20 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OperatingHours',
            fields=[
                ('hours_id', models.AutoField(primary_key=True, serialize=False)),
                ('hours_label', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='stall',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stalls.location'),
        ),
        migrations.AlterField(
            model_name='stall',
            name='operating_hours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stalls.operatinghours'),
        ),
    ]
